### ISSUE TITLE
debug/fix todo app errors

### ISSUE THREAD

**Issue by CorrectlyObserve** [CorrectlyObserve/FiCsJS#86]
## Summary

- Fix todo app errors

## Details [15/15]

- [x] Focusing input is canceled every time re-rendering is occurred in entering values.
  - [x] Correspond looped elements
  - [x] Correspond nested elements
  - [x] Correspond both looped and nested elements
  - [x] Correspond iframe element
  - [x] Correspond audio element
  - [x] Correspond video element
  - [x] Correspond object element
- [x] Fix the error about adding event listeners in re-rendering
- [x] Make using webkit prefix in css possible
- [x] Improve define method to make registering duplicated components possible
- [x] Fix tagged template literal to wrap fics instance with html element
- [x] Make getting the type of data automatically possible
- [x] Specify `:host` as default selector of css
- [x] Edit css to change orders of CSS-in-JS
- [x] Specify Event type
- [x] Fix type error of method in event arg of fics function
- [x] Renew HTMLElement rendered by instance after re-rendering
- [x] Fix the error of template literal of nesting html method
- [x] Fix the error of showing duplicated components
- [x]  Fix event handlers by both tag name and class name
- [x] Examine css transition

## Solutions

- We should consider using proxy to prevent re-creating input elements etc.
- We should implement like virtual DOM.

## Note (if any)

- Nothing
